### PR TITLE
Add environment variables to configure application

### PR DESCRIPTION
**Pull request by aladjadj**
* simplify configuration for docker environment

### CODE REVIEW

**Comment by aladjadj** [comment]
Solve #37

**Comment by felix-schmidt** [comment]
Hi @aladjadj , thanks for your contribution!

I like the idea of configuring Zubbi via envvars although this cannot be achieved for all settings this way e.g. `CONNECTIONS` as they are more complex. However, using this feature as a kind of backdoor to get the prefix into the Elasticsearch documents feels a little hacky to me.

If we go this way and allow configuration via envvars, it should be suitable for all settings and the same load order should apply to all.

With this change we would have three different load orders:
`ES_INDEX_PREFIX`: defaults -> envvars
`CONNECTIONS`: defaults -> settings.cfg
"Everything else": defaults -> settings.cfg -> envvars

IMHO this leads to confusion and makes it difficult to keep the list of settings clean (as they are now managed in two places).

Is there any other use case to configure Zubbi via envvars - apart from the `ES_INDEX_PREFIX`? I understand the docker part but to configure the `CONNECTIONS` you would need to put a file in the container anyways.

If we want to configure also the `CONNECTIONS` via envvars, we could think about namespaced-envvars like `CON_<CON_NAME>_URL` or `CON_<CON_NAME>_USER` but I'm not sure if that's a good idea as it makes the whole configuration much more complex.

**Comment by aladjadj** [comment]
Thx for your great feeback.

> I like the idea of configuring Zubbi via envvars although this cannot be achieved for all settings this way e.g. `CONNECTIONS` as they are more complex. However, using this feature as a kind of backdoor to get the prefix into the Elasticsearch documents feels a little hacky to me.

I'm ok with you about ES_INDEX_PREFIX but it's prerequis for me, i'm not proud about this part of code. So i can delete it from this PR :+1: 

> If we go this way and allow configuration via envvars, it should be suitable for all settings and the same load order should apply to all.
> 
> With this change we would have three different load orders:
> `ES_INDEX_PREFIX`: defaults -> envvars
> `CONNECTIONS`: defaults -> settings.cfg
> "Everything else": defaults -> settings.cfg -> envvars
> 
> IMHO this leads to confusion and makes it difficult to keep the list of settings clean (as they are now managed in two places).
> 
> Is there any other use case to configure Zubbi via envvars - apart from the `ES_INDEX_PREFIX`? I understand the docker part but to configure the `CONNECTIONS` you would need to put a file in the container anyways.
> 
> If we want to configure also the `CONNECTIONS` via envvars, we could think about namespaced-envvars like `CON_<CON_NAME>_URL` or `CON_<CON_NAME>_USER` but I'm not sure if that's a good idea as it makes the whole configuration much more complex.

Ok, i look for implement CONNECTION from envvars.
For you proposal about `CON_<CON_NAME>_*` the solution is:
```
CON_OPENSTACK_GERRIT_NAME=openstack-gerrit
CON_OPENSTACK_GERRIT_PROVIDER=gerrit
CON_OPENSTACK_GERRIT_URL=https://git.openstack.org
CON_OPENSTACK_GERRIT_WEB_URL=https://git.openstack.org/cgit
....
```
it's not a bad idea, but can we implement the envvars CONNECTION with Json for the moment, and in the second times a new version more elegant?

**Comment by westphahl** [comment]
Implemented by #41

**Comment by felix-schmidt** [comment]
@aladjadj We just closed this PR because as far as I know it originated in https://github.com/bmwcarit/zubbi/issues/37. If the configuration via environment variables is still an open point for you, we could reopen this one, but should think about a proper way to implement this feature without making the configuration part to difficult.

**Comment by aladjadj** [comment]
Hi @felix-schmidt ,
Sorry for the delay of response.
I have solved the problem in K8s with a configmap and a volumemount to add files on start.
Thx for the implementation of ES Index  #41 :+1: 
zuubi is alive @ [leboncoin](http://leboncoin.tech) :)

**Pull request closed without merging**
